spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 980527kmseok@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret:
    key: +8UjV8X8IfgAaA3g7gYfQg2R9r4LgkL1LwX+6T3a5A=